
# The config file is written using TOML, which stands for "Tom's Obvious,
# Minimal Language". See: https://github.com/toml-lang/toml



# The URL for your website. It should end with a trailing slash,
# e.g. "https://example.com/". If you're planning to deploy on
# GitHub pages the way I've done for the example site at
# https://djnavarro.github.io/hugo-slum/, then you can do something
# like this:
baseurl = "/waffle-blog/"



# Rewrite relative URLs to be relative to the current content.
relativeurls = true



# Default is "public", but if you're using github pages you
# need to point this to "docs".
publishDir = "docs"



# These settings specify the title for your blog, and the name of
# the Hugo theme that it uses.
title = "Spotify Through the Decades"
theme = "hugo-slum"



# Settings inherited from XMin theme that I haven't bothered to
# to edit in any way
languageCode = "en-us"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"



# What format should the permalinks take? In the example site there
# are two kinds of pages, posts and projects, listed at:
#
#    https://djnavarro.github.io/hugo-slum/post/
#    https://djnavarro.github.io/hugo-slum/project/
#
# Each post is then followed by its own "slug", so the full path
# might be something like this:
#
#     https://djnavarro.github.io/hugo-slum/post/getting-started/
#
[permalinks]
    post = "/post/:slug/"
    project = "/project/:slug/"
#
# Alternative version:
#   post = "/post/:year/:month/:day/:slug/"
#   project = "/project/:year/:month/:day/:slug/"



# These settings are used to specify the links in the main
# navigation bar. Each item has a "name" (the link text), a
# "url" (path to the page), and a "weight" (the order).
# Something to keep in mind for new users: you won't find
# specific files that correspond to all of these pages. See
# the documentation for an explanation of where they come from
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "1950's"
    url = "/1950s/"
    weight = 2
[[menu.main]]
    name = "1960's"
    url = "/1960s/"
    weight = 3
[[menu.main]]
    name = "1970's"
    url = "/1970s/"
    weight = 4
[[menu.main]]
    name = "1980's"
    url = "/1980s/"
    weight = 5
[[menu.main]]
    name = "1990's"
    url = "/1990s/"
    weight = 6
[[menu.main]]
    name = "2000's"
    url = "/2000s/"
    weight = 7
[[menu.main]]
    name = "2010's"
    url = "/2010s/"
    weight = 8
[[menu.main]]
    name = "Wrap Up"
    url = "/wrapup/"
    weight = 9



# Parameters used in various places throughout the site.
#
# - "siteHeader" specifies the default image used at the top of
#   every page (you can override it for specific posts). The
#   path to the image is specified relative to the "static/"
#   folder
#
# - "siteProfile" as above, but for the inset profile image.
#
# - "colourScheme" specifies a path to a css file that describes
#   the colour scheme, again relative to the "static/" folder. As
#   before you can override it for specific posts.
#
# - "description" of the site
# - "footer" contents
[params]
    siteHeader = "header/pink_performer_crop.jpg"
    twitterImage = "https://naomi-r.github.io/waffle-blog/header/waffle_PNG78.png"
    colourScheme = "css/palette_black.css"
    description = "An analysis of Spotify's trends in popular music over time"
    footer = "&copy; [Naomi Rahman](https://github.com/naomi-r) 2020 | [Visit Spotify](https://www.spotify.com/)"